Agencia prrona :v
AnhellO/DAS_Sistemas pull request #10
Opened 2017-09-10 18:04 UTC by gendersoon

2017-09-12 04:20 UTC, AnhellO commented
Bien Iván! 👍 . Faltó terminar el workflow en el `main.py`, y los diagramas también.

Algo que note es que tu fork no está actualizado con los cambios más recientes en el repo de la materia:

<img width="607" alt="screenshot 2017-09-11 00 03 56" src="https://user-images.githubusercontent.com/7515146/30259137-cb8241d0-9684-11e7-98f9-cf8445aba885.png">

Tendrás que actualizarlo antes de hacer merge a tus cambios. De igual manera, para la carpeta de alumno solamente basta con que coloques tu primer nombre y primer apellido ej. `Ivan Carreón/Práctica 1`. La carpeta del semestre ya está hecha, así que una vez que actualices tu fork deberías de poder mover tus archivos sin problemas. Házme saber si tienes alguna duda 👍

2017-09-12 04:22 UTC, AnhellO requested changes
Bien Iván! 👍 . Faltó terminar el workflow en el `main.py`, y los diagramas también.

Algo que note es que tu fork no está actualizado con los cambios más recientes en el repo de la materia:

<img width="607" alt="screenshot 2017-09-11 00 03 56" src="https://user-images.githubusercontent.com/7515146/30259137-cb8241d0-9684-11e7-98f9-cf8445aba885.png">

Tendrás que actualizarlo antes de hacer merge a tus cambios. De igual manera, para la carpeta de alumno solamente basta con que coloques tu primer nombre y primer apellido ej. `Ivan Carreón/Práctica 1`. La carpeta del semestre ya está hecha, así que una vez que actualices tu fork deberías de poder mover tus archivos sin problemas. Házme saber si tienes alguna duda 👍

2017-09-12 04:22 UTC, AnhellO commented on Semestre7/Ivan_Alejandro_Carreon_Silva/practica-1/Vehiculo.py
> +    def incrementaExist(self,n):
Método similar al de la clase Vehiculo de Omar. ¿Cómo es que funciona este incremento? 🤔

2017-09-12 04:22 UTC, AnhellO commented on Semestre7/Ivan_Alejandro_Carreon_Silva/practica-1/main.py
> +        print('Estamos trabajando en eso :v')
Pos ya fue :'v

2017-09-12 22:58 UTC, gendersoon commented on Semestre7/Ivan_Alejandro_Carreon_Silva/practica-1/Vehiculo.py
> +    def incrementaExist(self,n):
tenia pensado que se incrementara la existencia de un carro al momento de que la agencia comprara, pero no supe como x'D

2017-09-12 23:06 UTC, gendersoon commented on Semestre7/Ivan_Alejandro_Carreon_Silva/practica-1/main.py
> +        print('Estamos trabajando en eso :v')
una duda,como puedo actualizar mi repo con lo que añadio recientemente? 🤔

2017-09-13 05:00 UTC, AnhellO commented on Semestre7/Ivan_Alejandro_Carreon_Silva/practica-1/Vehiculo.py
> +    def incrementaExist(self,n):
😐

2017-09-13 05:05 UTC, AnhellO commented on Semestre7/Ivan_Alejandro_Carreon_Silva/practica-1/main.py
> +        print('Estamos trabajando en eso :v')
Acá un par de tutos del funcionamiento de los forks Iván, espero te sean de ayuda:

- https://guides.github.com/activities/forking/
- https://help.github.com/articles/syncing-a-fork/

El segundo es el que te vendrá mejor 👍

2017-09-13 18:51 UTC, gendersoon commented on Semestre7/Ivan_Alejandro_Carreon_Silva/practica-1/main.py
> +        print('Estamos trabajando en eso :v')
y una vez hecho el merge hago pr otra vez? 🤔

2017-09-13 19:49 UTC, gendersoon commented on Semestre7/Ivan_Alejandro_Carreon_Silva/practica-1/main.py
> +        print('Estamos trabajando en eso :v')
le mande unos mensajes por fb 👍

2017-09-16 07:17 UTC, AnhellO commented
Dejé algunos comentarios a través del chat en Facebook, pero los agrego aquí para motivos de documentación:

Tienes que mover tu carpeta a la carpeta del semestre: `Ago-Dic-2017`, y una ves ahí, tu carpeta de alumno debe de quedar como `Ivan Carreón`, sin guión bajo `_`. Puedes checarlo en la parte de [Contributing](https://github.com/AnhellO/DAS_Sistemas#contributing) del README file. Dime si tienes alguna duda sobre esto Iván 👍

2017-09-17 01:23 UTC, AnhellO approved these changes

2017-09-17 01:23 UTC, AnhellO commented
Listo 👍 !

2017-09-17 01:23 UTC, merged