Práctica 1
AnhellO/DAS_Sistemas pull request #12
Opened 2017-09-10 22:03 UTC by ecete

2017-09-12 04:49 UTC, AnhellO requested changes
Bien Enrique 👍 !. Falto el diagrama de actividades, pero lo demás se ve bien. Como único cambio necesario antes de hacer merge, es que te apegues a la [forma de contribuir en el repositorio](https://github.com/AnhellO/DAS_Sistemas#contributing), por favor Enrique. Dime si tienes alguna duda con esto 👍

2017-09-15 05:52 UTC, ecete commented
Agruegado diagrama de actividades

2017-09-16 06:08 UTC, AnhellO commented
Qué tal Enrique!

Falta nada más que ajustes tu carpeta de alumno, y la muevas a la carpeta del semestre que ya está creada, tal como lo dice el README en la parte de cómo contribuir: https://github.com/AnhellO/DAS_Sistemas#contributing

Una vez que quedé listo esto, le hacemos merge al repo principal 👍

2017-09-19 04:45 UTC, ecete commented
Cambios en la carpeta de alumno

2017-09-19 04:47 UTC, ecete commented
Cambios en la carpeta de alumno

2017-09-19 04:57 UTC, AnhellO commented
Muy bien, listo Enrique 👍 !

2017-09-19 04:58 UTC, AnhellO approved these changes

2017-09-19 04:58 UTC, merged