DAS_Sistemas development Push:Practica 1
AnhellO/DAS_Sistemas pull request #172
Opened 2020-09-02 21:50 UTC by Danieldm16

Estuve leyendo de los recursos y vi algunos vídeos sobre listas y clases, intente explicar todo de la mejor forma posible y creo que ya quedo la practica, espero que esté bien.

2020-09-03 05:04 UTC, AnhellO reviewed
Muy bien @Danieldm16!

Dejé algunos comentarios, avísame si tienes dudas 👍

2020-09-03 05:04 UTC, AnhellO commented on Ago-Dic-2020/salazar-coronado-juan-daniel/practica1/practica1.py
> +        self.matrizcompleta = matrix_string.split()
No es necesario agregar este atributo

2020-09-03 05:04 UTC, AnhellO commented on Ago-Dic-2020/salazar-coronado-juan-daniel/practica1/practica1.py
> +        self.matrizfilas = [[x for x in i.split()] for i in matrix_string.splitlines()]
Hay que convertir los valores de la matriz `string` a `int` 😉

2020-09-03 05:04 UTC, AnhellO commented on Ago-Dic-2020/salazar-coronado-juan-daniel/practica1/practica1.py
> +        self.fila = self.matrizfilas[index-1]
No es necesario asignar el valor a un atributo de instancia, puedes retornarlo directamente y como una copia. El retornar una copia evitará que la matriz original sea alterada: https://www.afternerd.com/blog/python-copy-list/

2020-09-03 05:04 UTC, AnhellO commented on Ago-Dic-2020/salazar-coronado-juan-daniel/practica1/practica1.py
> +        return self.columna
Aquí también puedes retornar directamente sin necesidad de asignar a una variable de instancia 👍

2020-09-03 18:19 UTC, Danieldm16 commented
Ya agregue los cambios que sugirió y también lo de convertir los valores de la matriz de string a int 👍

2020-09-07 05:48 UTC, AnhellO requested changes
Solamente un comment más y estamos listos 👍

2020-09-07 05:48 UTC, AnhellO commented on Ago-Dic-2020/salazar-coronado-juan-daniel/practica1/practica1.py
> +        return self.fila[index-1]
Aquí podemos retornar el índice de la copia directa, sin necesidad de asignar a `self.fila`

2020-09-07 15:03 UTC, Danieldm16 commented
Ya quedo ese cambio también

2020-09-07 15:11 UTC, AnhellO approved these changes

2020-09-07 15:11 UTC, merged