Commit de practica 1
AnhellO/DAS_Sistemas pull request #188
Opened 2020-09-06 11:09 UTC by JesusAGC

Practica 1

2020-09-07 05:32 UTC, AnhellO requested changes
Hay que nombrar el pull request de la manera correcta de acuerdo a https://github.com/AnhellO/DAS_Sistemas/blob/development/README.md#contributing

2020-09-07 05:32 UTC, AnhellO commented on Ago-Dic-2020/gonzalez-cardenas-jesus-antonio/Practica 1/Matriz.py
> +
Recomiendo quitar este espacio extra

2020-09-07 05:32 UTC, AnhellO commented on Ago-Dic-2020/gonzalez-cardenas-jesus-antonio/Practica 1/Matriz.py
> +        self._matrix_string = [[int(row_item) for row_item in row.split()] for row in matrix_string.split("\n")]
Dale un vistazo a https://docs.python.org/3/library/stdtypes.html#str.splitlines 😉

2020-09-07 05:32 UTC, AnhellO commented on Ago-Dic-2020/gonzalez-cardenas-jesus-antonio/Practica 1/Matriz.py
> +        return self._matrix_string[index - 1]
¿Qué sucedería si modificamos la fila que se retorna desde aquí?, es decir `fila = row(1)` y luego `fila = [1, 2, 5]`

2020-09-14 02:05 UTC, JesusAGC commented
Ya corregí los espacios

2020-09-21 04:46 UTC, AnhellO requested changes

2020-09-21 04:46 UTC, AnhellO commented on Ago-Dic-2020/gonzalez-cardenas-jesus-antonio/Practica 1/Matriz.py
> +
También es preferible no dejar espacio entre la declaración de una función, y el inicio de su lógica, es decir:
```python
def x():
    pass
```

2020-09-21 04:46 UTC, AnhellO commented on Ago-Dic-2020/gonzalez-cardenas-jesus-antonio/Practica 1/Matriz.py
> +        self._matrix_string = [[int(row_item) for row_item in row.split()] for row in matrix_string.split("\n")]
¿Revisamos esta sugerencia?: https://github.com/AnhellO/DAS_Sistemas/pull/188#discussion_r484190690

2020-10-06 04:06 UTC, merged