Práctica 1 damn
AnhellO/DAS_Sistemas pull request #191
Opened 2020-09-07 04:02 UTC by developer-jesus-github

Sorry, estuve participando en un concurso nacional de hacking con diego e iván (alumno y ex alumno de la clase) y se me pasó enviarla... woops... por suerte clasificamos top 3 en el concurso. Nuevamente una disculpa, no volverá a pasar.

2020-09-07 05:59 UTC, AnhellO requested changes
Felicidades por ese 3er lugar 👏 .

Hay que nombrar el pull request de la manera correcta de acuerdo a https://github.com/AnhellO/DAS_Sistemas/blob/development/README.md#contributing

2020-09-07 05:59 UTC, AnhellO commented on Ago-Dic-2020/rodriguez-martinez-jesus-angel/Practica-1/Practica-1.py
> +            return self.data[row_position-1]
No hay que preocuparnos por la validación de momento, podemos retornar el valor sin mayores preocupaciones 😉. Lo que si es que te aconsejo revisar https://www.afternerd.com/blog/python-copy-list/

2020-09-07 05:59 UTC, AnhellO commented on Ago-Dic-2020/rodriguez-martinez-jesus-angel/Practica-1/Practica-1.py
> +            return self.data[row_position-1]
Y acá una sugerencia para futuras refactorizaciones (aunque al final no será usado...): No hay necesidad del `else` si ya estamos retornando un valor dentro del `if` 😉

2020-09-07 05:59 UTC, AnhellO commented on Ago-Dic-2020/rodriguez-martinez-jesus-angel/Practica-1/Practica-1.py
> +    def validateRow(self, row_position):
No necesitamos esta función

2020-09-07 05:59 UTC, AnhellO commented on Ago-Dic-2020/rodriguez-martinez-jesus-angel/Practica-1/Practica-1.py
> +    def getColumn(self, column_position):
Mismos comentarios que con `getRow`

2020-09-07 05:59 UTC, AnhellO commented on Ago-Dic-2020/rodriguez-martinez-jesus-angel/Practica-1/Practica-1.py
> +    def getRow(self, row_position):
Te recomiendo el uso de `snake_case` por https://www.python.org/dev/peps/pep-0008/#id45

2020-09-10 06:11 UTC, developer-jesus-github commented on Ago-Dic-2020/rodriguez-martinez-jesus-angel/Practica-1/Practica-1.py
> +    def getRow(self, row_position):
Interesante la recomendación de PEP, en mi primer trabajo también me lo recomendaron y lo había olvidado por completo, muchas gracias por la recomendación!

2020-09-10 06:12 UTC, developer-jesus-github commented on Ago-Dic-2020/rodriguez-martinez-jesus-angel/Practica-1/Practica-1.py
> +    def getColumn(self, column_position):
Ya quedó, muchas gracias maestro

2020-09-10 06:12 UTC, developer-jesus-github commented on Ago-Dic-2020/rodriguez-martinez-jesus-angel/Practica-1/Practica-1.py
> +    def validateRow(self, row_position):
Función removida, muchas gracias maestro.

2020-09-10 06:12 UTC, developer-jesus-github commented on Ago-Dic-2020/rodriguez-martinez-jesus-angel/Practica-1/Practica-1.py
> +            return self.data[row_position-1]
Perfecto, retirado sin problemas, tiene toda la razón, muchas gracias por sus recomendaciones!

2020-09-10 17:46 UTC, AnhellO requested changes
Solamente un cambio menor más, pero se va viendo muy bien! :smile:

2020-09-10 17:46 UTC, AnhellO commented on Ago-Dic-2020/rodriguez-martinez-jesus-angel/Practica-1/Practica-1.py
> +        return list([row[column_position-1] for row in self.data])
Aquí no hay necesidad de usar la función `list()` porque ya estás regresando una nueva referencia por medio de la lista comprimida que generas :wink:

2020-10-06 04:08 UTC, merged