Practica 1 DAS
AnhellO/DAS_Sistemas pull request #192
Opened 2020-09-11 03:00 UTC by Rephyroth

Una disculpa por mandarlo hasta ahora, e estado tratando de aprender a usar Python y Git en general

2020-09-21 05:03 UTC, AnhellO requested changes

2020-09-21 05:03 UTC, AnhellO commented on Ago-Dic-2020/flores-fernandez-fernando/Practica-1.py
> +import numpy as np
Podemos utilizar las [listas nativas de python](https://entrenamiento-python-basico.readthedocs.io/es/latest/leccion3/tipo_listas.html), no es necesario utilizar `numpy.array`

2020-09-21 05:03 UTC, AnhellO commented on Ago-Dic-2020/flores-fernandez-fernando/Practica-1.py
> +    def __init__(self):
En esta función es en donde se supone que debemos de inicializar nuestra instancia de matriz, pasándole un argumento tipo string, que será el que convertiremos en una lista que contiene otras listas (o bien una matriz). Hay que verificar bien las especificaciones: https://github.com/AnhellO/DAS_Sistemas/blob/development/Ago-Dic-2020/Practicas/1er-Parcial/Pr%C3%A1ctica%201/SPECS.md#especificaciones

2020-09-21 05:03 UTC, AnhellO commented on Ago-Dic-2020/flores-fernandez-fernando/Practica-1.py
> +    def row(self):
Acá debemos de pasar el índice que queremos consultar

2020-09-21 05:03 UTC, AnhellO commented on Ago-Dic-2020/flores-fernandez-fernando/Practica-1.py
> +        matriz = [
Esta matriz no es necesaria acá. Se supone que nosotros debemos de construir las instancias de la clase `Matrix` por medio del constructor

2020-09-21 05:03 UTC, AnhellO commented on Ago-Dic-2020/flores-fernandez-fernando/Practica-1.py
> +        i = int(input("Numero de Fila que quisiera ver\n"))
Idealmente los `input` deben de manejarse por fuera de la lógica de las funciones, como parte del cliente y no de los objetos que estamos manipulando

2020-09-21 05:03 UTC, AnhellO commented on Ago-Dic-2020/flores-fernandez-fernando/Practica-1.py
> +        matriz = [
Mismo comentario que con la otra matriz

2020-09-21 05:03 UTC, AnhellO commented on Ago-Dic-2020/flores-fernandez-fernando/Practica-1.py
> +        print(fila)
Tenemos que retornar la `row` solicitado, y no imprimirla como tal

2020-09-21 05:03 UTC, AnhellO commented on Ago-Dic-2020/flores-fernandez-fernando/Practica-1.py
> +        i = int(input("Numero de Columna que quisiera ver\n"))
Mismo comentario que con el otro `input` en la función `row`

2020-09-21 05:03 UTC, AnhellO commented on Ago-Dic-2020/flores-fernandez-fernando/Practica-1.py
> +        print(columna)
Tenemos que retornar la columna solicitada

2020-09-21 05:03 UTC, AnhellO commented on Ago-Dic-2020/flores-fernandez-fernando/Practica-1.py
> +    def column(self):
Hay que pasar el índice de la columna. Verifica los specs una vez más por favor 😄

2020-09-21 05:03 UTC, AnhellO commented on Ago-Dic-2020/flores-fernandez-fernando/Practica-1.py
> +Matriz= Matrix()
Los objetos se crean preferentemente con letras minúsculas, números y guiones bajos

2020-10-05 00:14 UTC, Rephyroth commented on Ago-Dic-2020/flores-fernandez-fernando/Practica-1.py
> +import numpy as np
sip una disculpa, en el momendo que hice la practica , tenia mucho sin programar y bueno no sabia python pero ahi voy mejorando

2020-10-05 00:14 UTC, Rephyroth commented on Ago-Dic-2020/flores-fernandez-fernando/Practica-1.py
> +    def row(self):
sip ya lo cambie en la nueva practica

2020-10-05 00:16 UTC, Rephyroth commented on Ago-Dic-2020/flores-fernandez-fernando/Practica-1.py
> +Matriz= Matrix()
oka, ya cambie todo en el nuevo commit

2020-10-06 04:10 UTC, AnhellO approved these changes

2020-10-06 04:10 UTC, merged