DAS_Sistemas Develop Push: Practica 2
AnhellO/DAS_Sistemas pull request #194
Opened 2020-09-13 04:13 UTC by ERORESRA

2020-09-19 04:25 UTC, AnhellO requested changes
El diagrama se ve bien!

Dejé algunos comentarios respecto al código, házme saber si tienes alguna duda 👍

2020-09-19 04:25 UTC, AnhellO commented on Ago-Dic-2020/escarcega-ramirez-erick-orlando/Practicas/Practica-2/practica-2.py
> +        print(self.name.title() + " is now dancing.")
Recuerda que puedes utilizar el [`f string`](https://realpython.com/python-f-strings/) 😉 . Por ejemplo:
```python
f"{self.name.title()} is now dancing."
```

Esto también puedes aplicarlo a otras funciones aquí en tu clase.

2020-09-19 04:25 UTC, AnhellO commented on Ago-Dic-2020/escarcega-ramirez-erick-orlando/Practicas/Practica-2/practica-2.py
> +        Zoo.__init__(self, name, animal, species, food, age)
Échale un ojo a [`super()`](https://www.journaldev.com/15911/python-super) 😄

2020-09-19 04:25 UTC, AnhellO commented on Ago-Dic-2020/escarcega-ramirez-erick-orlando/Practicas/Practica-2/practica-2.py
> +
Tratemos de ser consistentes con los espacios entre funciones y clases

2020-09-19 04:27 UTC, ERORESRA commented on Ago-Dic-2020/escarcega-ramirez-erick-orlando/Practicas/Practica-2/practica-2.py
> +        Zoo.__init__(self, name, animal, species, food, age)
Si lo vi en el libro de crash course! lo implementare en la practica!

2020-10-06 04:15 UTC, AnhellO approved these changes

2020-10-06 04:16 UTC, merged