Practica2das sistemas
AnhellO/DAS_Sistemas pull request #196
Opened 2020-09-13 08:36 UTC by Danieldm16

Practica 2 completa

2020-09-13 08:42 UTC, Danieldm16 commented
Profesor tengo una duda, como se hacía para regresar a la branch de desarrollo despues de hacer el git push para subir los archivos a la branch exclusiva que se crea de la practica?, o solo sería estar cambiando de branch cada que haga una practica?

2020-09-21 05:35 UTC, AnhellO requested changes
Hay que nombrar el pull request correctamente:

Respecto a tu pregunta:
> Profesor tengo una duda, como se hacía para regresar a la branch de desarrollo despues de hacer el git push para subir los archivos a la branch exclusiva que se crea de la practica?, o solo sería estar cambiando de branch cada que haga una practica?

Puedes estar cambiando entre la branch de cada práctica, no hay problema, en teoría ya no volverías a tocar la branch de `development`, pero si quieres moverte de regreso a esa branch (aplica también para cualquier otra branch), basta con utilizar `git checkout nombre-de-mi-branch`, por ejemplo `git checkout development` o `git checkout practica2das_sistemas`

2020-09-21 05:35 UTC, AnhellO commented on Ago-Dic-2020/salazar-coronado-juan-daniel/practica2/practica2.py
> +    def getCarrera(self):
El nombre de las funciones en python tiene que ser estilo `snake_case`, de acuerdo al estándar oficial: https://www.python.org/dev/peps/pep-0008/#function-and-variable-names

2020-09-21 05:35 UTC, AnhellO commented on Ago-Dic-2020/salazar-coronado-juan-daniel/practica2/practica2.py
> +        return "Soy " + self.nombre + ", tengo " + self.edad + " años y estoy en " + self.semestre + " semestre."
Te recomiendo aprender a hacer uso de los [`f strings` en python](https://realpython.com/python-f-strings/) 😉

2020-09-21 05:35 UTC, AnhellO commented on Ago-Dic-2020/salazar-coronado-juan-daniel/practica2/practica2.py
> +        'ISC': "Ing. En sistemas computacionales",
Tratemos de darle indentación a los elementos de este diccionario, es decir:
```python
carreras = {
    'ISC': "Ing. En sistemas computacionales",
    'IIS': "Ing. Industrial y de sistemas",
}
```

2020-09-21 05:35 UTC, AnhellO commented on Ago-Dic-2020/salazar-coronado-juan-daniel/practica2/practica2.py
> +        else:
Si ya estás retornando dentro de los bloques `if` anteriores, entonces ya no es necesario utilizar `else` y `elif`, porque en teoría el código ya no va a llegar a ese punto 😉

2020-09-21 05:35 UTC, AnhellO commented on Ago-Dic-2020/salazar-coronado-juan-daniel/practica2/practica2.py
> +        Estudiante.__init__(self, nombre, edad, semestre, carrera)
Te recomiendo darle un vistazo a [`super()`](https://www.journaldev.com/15911/python-super)

2020-09-21 05:35 UTC, AnhellO commented on Ago-Dic-2020/salazar-coronado-juan-daniel/practica2/practica2.py
> +        elif self.servicio == False and self.practicas == True:
Mismo comentario para estos `elif` blocks

2020-09-21 05:35 UTC, AnhellO commented on Ago-Dic-2020/salazar-coronado-juan-daniel/practica2/practica2.py
> +        if self.servicio == True and self.practicas == True:
Una buena técnica para reducir el código acá es por default evaluar el valor de la variable booleana sin necesidad de compararla, es decir: `if self.servicio == True and self.practicas == True:` es igual a `if self.servicio and self.practicas:` 😉

2020-09-21 05:35 UTC, AnhellO commented on Ago-Dic-2020/salazar-coronado-juan-daniel/practica2/practica2.py
> +        elif self.servicio == False and self.practicas == False:
Mismo comentario sobre utilizar el valor de los booleanos como default para las evaluaciones lógicas, solamente que en este caso tendríamos que utilizar la negación, por estar evaluando un valor `False`, es decir `if self.servicio == False and self.practicas == False:` es igual a `if not self.servicio and not self.practicas:`

2020-09-21 05:35 UTC, AnhellO commented on Ago-Dic-2020/salazar-coronado-juan-daniel/practica2/practica2.py
> +    def getCarrera(self):
Esto aplica para todas las funciones y variables que puedan ser actualizadas en esta práctica (y en futuras prácticas) 😄

2020-10-01 23:35 UTC, Danieldm16 commented
Disculpe la tardanza profesor, entre tareas y trabajo está difícil, pero ya realice todos los cambios que me pidio.

2020-10-06 04:20 UTC, AnhellO requested changes
Un par de comentarios más, pero se va viendo bien 👍

2020-10-06 04:20 UTC, AnhellO commented on Ago-Dic-2020/salazar-coronado-juan-daniel/practica2/classes.dot
> +charset="utf-8"
El diagrama debe de actualizarse, ya que el nombre de algunas funciones cambiaron debido a la actualización solicitada en https://github.com/AnhellO/DAS_Sistemas/pull/196#discussion_r491799281

2020-10-06 04:20 UTC, AnhellO commented on Ago-Dic-2020/salazar-coronado-juan-daniel/practica2/practica2.py
> +        if self.servicio == True and self.practicas == False:
Aquí todavía podemos mejorarlo a `if self.servicio and not self.practicas`. Lo mismo para `if` de la parte de abajo

2020-10-06 16:42 UTC, Danieldm16 commented
Realizados los cambios que me comento profesor.

2020-10-07 02:01 UTC, AnhellO approved these changes

2020-10-07 02:02 UTC, merged