DAS_Sistemas Develop Push:Practica2
AnhellO/DAS_Sistemas pull request #198
Opened 2020-09-13 15:12 UTC by Jahirrlly

No se porque, pero puedo usar el comando dot aunque tengo ya instalado graphviz correctamente, por eso no pude hacer el diagramita UML.

2020-09-23 03:25 UTC, AnhellO requested changes
> No se porque, pero puedo usar el comando dot aunque tengo ya instalado graphviz correctamente, por eso no pude hacer el diagramita UML.

Es posible poder ayudarte, pero necesito saber, ¿qué errores te envió?

2020-09-23 03:25 UTC, AnhellO commented on Ago-Dic-2020/perez-sanchez-jose-jahir/Practica2/Practica2.py
> +    def IMC(self):
Las funciones y los nombres de variables deben de estar en minúsculas: https://www.python.org/dev/peps/pep-0008/#function-and-variable-names

2020-09-23 03:25 UTC, AnhellO commented on Ago-Dic-2020/perez-sanchez-jose-jahir/Practica2/Practica2.py
> +        Animal.__init__(self,edad,tamaño,peso,altura)
Te recomiendo utilizar la función [`super()`](https://realpython.com/python-super/)

2020-09-23 18:41 UTC, Jahirrlly commented
Me envio el error de que el comando dot no existe y ya reinstale el graphiz varias veces pero nomas no detecta que existe ese comando y si me dice que esta instalado correctamente

2020-09-24 04:56 UTC, AnhellO approved these changes
> Me envio el error de que el comando dot no existe y ya reinstale el graphiz varias veces pero nomas no detecta que existe ese comando y si me dice que esta instalado correctamente

Posiblemente sea tema del path después de la instalación. En Windows comúnmente hay que configurar las variables de entorno para poder agregar un nuevo ejecutable al path del sistema (no es como en sistemas UNIX). Te recomiendo revisar alguno de los siguientes tutoriales para verificar la instalación e intentarla de nuevo de ser necesario:
- https://www.youtube.com/watch?v=JYAHwQ_tMG0
- https://www.youtube.com/watch?v=WkLhdBbf-3E
- https://www.youtube.com/watch?v=Ti2Br2Pq_A4

Intenta con lo anterior, y en caso de que no sea posible, hagamos la prueba de buscar otra alternativa para generar los diagramas UML (la que tu gustes), o bien, podemos hacerlos por medio de Power Point, Paint, o hasta a mano (y subir una fotografía de ser necesario).

2020-09-24 04:57 UTC, AnhellO commented
Por cierto, hay que borrar el archivo de `Ago-Dic-2020/perez-sanchez-jose-jahir/Practica1/Practica1.py` que se agregó en este pull request, ya que el del otro pull request ya fue aprobado 👍

2020-10-06 04:24 UTC, AnhellO approved these changes

2020-10-06 04:24 UTC, merged