DAS_Sistemas Develop Push: Practica-2
AnhellO/DAS_Sistemas pull request #203
Opened 2020-09-14 03:37 UTC by developer-jesus-github

Hace falta mucha refactorización, uso de diccionarios, los kargs y demás pero por el trabajo recién pude empezarla ahorita y la terminé antes de que se acabara el tiempo, toca organizar mejor el tiempo, saludos profe :)!

2020-09-19 05:11 UTC, AnhellO requested changes
Unos cuantos comentarios. El diagrama está bien, solamente es posible que haya que actualizarlo después de actualizar las clases 👍

2020-09-19 05:11 UTC, AnhellO commented on Ago-Dic-2020/rodriguez-martinez-jesus-angel/Practica-2/Practica-2.py
> +        Anime.__init__(self, title, episodes, status, aired, score, ranked, popularity, english, synonyms, japanese)
Échale un ojo a [`super()`](https://www.journaldev.com/15911/python-super) 😉

2020-09-19 05:11 UTC, AnhellO commented on Ago-Dic-2020/rodriguez-martinez-jesus-angel/Practica-2/Practica-2.py
> +    def __init__ (self, title, episodes, status, aired, score, ranked, popularity, english, synonyms, japanese):
> Hace falta mucha refactorización, uso de diccionarios, los kargs y demás pero por el trabajo recién pude empezarla ahorita y la terminé antes de que se acabara el tiempo, toca organizar mejor el tiempo, saludos profe :)!

No te preocupes, para eso viene después el flujo de code-review/código-colaborativo. Mientras hayas enviado tu práctica con tu approach inicial dentro de los límites de tiempo estamos bien. Aparte hay que recordar la famosa frase de https://softwareengineering.stackexchange.com/q/80084/271959 😉 

Dicho esto, podemos proceder a hacer uso de los `kwargs` para mejorar la práctica 👍

2020-09-19 05:11 UTC, AnhellO commented on Ago-Dic-2020/rodriguez-martinez-jesus-angel/Practica-2/Practica-2.py
> +    def set_character_name(self, character_name):
En caso de que estemos usando `setters` y `getters` entonces asegurémonos de utilizar atributos privados y/o protegidos 👍

2020-09-27 22:37 UTC, developer-jesus-github commented on Ago-Dic-2020/rodriguez-martinez-jesus-angel/Practica-2/Practica-2.py
> +    def set_character_name(self, character_name):
Ya lo modifiqué, me ayudaría mucho su retroalimentación, sin piedad profe, todo lo que esté mal lo cambio sin problema, saludos.

2020-09-27 22:38 UTC, developer-jesus-github commented on Ago-Dic-2020/rodriguez-martinez-jesus-angel/Practica-2/Practica-2.py
> +        Anime.__init__(self, title, episodes, status, aired, score, ranked, popularity, english, synonyms, japanese)
Lo intenté implementar, espero haberlo hecho bien, sino lo vuelvo a cambiar, saludos!

2020-10-06 04:37 UTC, AnhellO requested changes
Un pequeño comentario más y estamos listos 👍

2020-10-06 04:37 UTC, AnhellO commented on Ago-Dic-2020/rodriguez-martinez-jesus-angel/Practica-2/Practica-2.py
> +        super().__init__()
Un pequeño bug por acá. Ojo que no estás pasando los `**kwargs` al constructor de la clase padre, por ende los atributos heredados para las instancias de `Character` no tienen algún valor:
```
Information: 
Title: Zankyou no Terror (VON) 
Episodes: 11 
Status: Finished Airing 
Aired: Jul 11, 2014 to Sep 26, 2014

Statistics: 
Score: 8.14 
Ranked: #368 
Popularity: #90

Alternative Titles: 
English: Terror in Resonance 
Synonysm: Terror in Tokyo, Terror of Resonance 
Japanese: 残響のテロル

Character name: Twelve
Character description: He is a member of sphinx LOL

Character name: Nine
Character description: He is a member of sphinx LOL

Information: 
Title:  
Episodes:  
Status:  
Aired: 
```

2020-10-06 04:37 UTC, AnhellO commented on Ago-Dic-2020/rodriguez-martinez-jesus-angel/Practica-2/Practica-2.py
> +        Anime.__init__(self, title, episodes, status, aired, score, ranked, popularity, english, synonyms, japanese)
Relacionado: https://github.com/AnhellO/DAS_Sistemas/pull/203#pullrequestreview-502577430

2020-10-08 18:30 UTC, developer-jesus-github commented on Ago-Dic-2020/rodriguez-martinez-jesus-angel/Practica-2/Practica-2.py
> +        super().__init__()
Ya quedó, cualquier cosa ando al pendiente, gracias por todo maestro!

2020-10-12 04:14 UTC, AnhellO approved these changes

2020-10-12 04:14 UTC, merged