DAS_Sistemas Develop Push: Practica-3
AnhellO/DAS_Sistemas pull request #211
Opened 2020-09-17 17:06 UTC by Rephyroth

2020-10-06 05:52 UTC, AnhellO requested changes
Un pequeño cambio

2020-10-06 05:52 UTC, AnhellO commented on Ago-Dic-2020/flores-fernandez-fernando/Practicas/Practica-3/Practica-3.py
> +    def changeState(self):
Hay que ajustar los nombres de funciones y variables a que cumplan con [pep-8](https://www.python.org/dev/peps/pep-0008/)

2020-10-06 22:24 UTC, Rephyroth commented on Ago-Dic-2020/flores-fernandez-fernando/Practicas/Practica-3/Practica-3.py
> +    def changeState(self):
ok, ya modifique las funciones y las variables segun pep-8, y modifique el test_practica3, para usar unittest

2020-10-07 01:56 UTC, AnhellO approved these changes

2020-10-07 01:56 UTC, merged