DAS_Sistemas develop push: Practica 2
AnhellO/DAS_Sistemas pull request #218
Opened 2020-09-21 22:27 UTC by DavidSMtz

2020-09-23 04:35 UTC, AnhellO requested changes
Otro comentario: No veo el diagrama UML

2020-09-23 04:35 UTC, AnhellO commented on Ago-Dic-2020/sena-martinez-angel-david/Practica2.py
> +    def _str_(self):
`__str__` es un [magic method](https://www.geeksforgeeks.org/dunder-magic-methods-python/) en python, por lo tanto hay que utilizar doble guión bajo en su definición

2020-09-23 04:35 UTC, AnhellO commented on Ago-Dic-2020/sena-martinez-angel-david/Practica2.py
> +    def pesoideal(self):
Nombres de funciones y variables deben de ser `snake_case` por recomendaciones del [estándar oficial](https://www.python.org/dev/peps/pep-0008/#function-and-variable-names)

2020-09-23 04:35 UTC, AnhellO commented on Ago-Dic-2020/sena-martinez-angel-david/Practica2.py
> +    def hijos(self,sons):
Espacio faltante entre los parámetros

2020-09-23 04:35 UTC, AnhellO commented on Ago-Dic-2020/sena-martinez-angel-david/Practica2.py
> +        return f"{self.nombre} tiene {self.edad} años, su peso es de {self.peso}y su altura es de {self.altura} cm."
Espacio faltante entre `{self.peso}` e `y`

2020-09-23 04:35 UTC, AnhellO commented on Ago-Dic-2020/sena-martinez-angel-david/Practica2.py
> +        Persona.__init__(self,edad,peso,altura)
Dale un vistazo a [`super()`](https://www.journaldev.com/15911/python-super) 😉

2020-09-23 04:35 UTC, AnhellO commented on Ago-Dic-2020/sena-martinez-angel-david/Practica2/Practica2.py
> +class Persona():
Veo 2 veces el archivo, ¿cuál es el bueno? 🤔

2020-09-23 23:17 UTC, DavidSMtz commented on Ago-Dic-2020/sena-martinez-angel-david/Practica2.py
> +    def hijos(self,sons):
Ya lo corregí profe

2020-09-23 23:17 UTC, DavidSMtz commented on Ago-Dic-2020/sena-martinez-angel-david/Practica2/Practica2.py
> +class Persona():
Es el DAS_ sistemas develop push

2020-09-24 06:00 UTC, AnhellO commented on Ago-Dic-2020/sena-martinez-angel-david/Practica2.py
> +    def hijos(self,sons):
No veo los cambios aplicados en este pull request @DavidSMtz

2020-10-06 06:06 UTC, AnhellO requested changes
¿Qué hay con el diagrama UML?, ¿pudo generarse o no?.

En caso de no poder utilizar la librería, se puede adjuntar el diagrama como imágen o PDF, generado por alguna otra herramienta (incluso hasta a mano de ser necesario)

2020-10-06 06:06 UTC, AnhellO commented on Ago-Dic-2020/sena-martinez-angel-david/Practica2.py
> +        self.nombre=nombre
Necesitamos respetar los espacios para los operadores aritméticos y de asignación de acuerdo a [pep-8](https://www.python.org/dev/peps/pep-0008/)

2020-10-06 06:06 UTC, AnhellO commented on Ago-Dic-2020/sena-martinez-angel-david/Practica2.py
> +        Persona.__init__(self,edad, peso, altura)
Sigue pendiente de implementar el comentario de `super()` https://github.com/AnhellO/DAS_Sistemas/pull/218#discussion_r493191567

2020-10-06 06:06 UTC, AnhellO commented on Ago-Dic-2020/sena-martinez-angel-david/Practica2/Practica2.py
> +class Persona():
Sigo viendo dos archivos, uno como `../Practica2/Practica2.py` y otro como `../Practica2.py`

2020-10-07 03:48 UTC, AnhellO requested changes
Sigue habiendo varios cambios pendientes de implementar, los enumero a continuación:
- https://github.com/AnhellO/DAS_Sistemas/pull/218#discussion_r493191567
  - https://github.com/AnhellO/DAS_Sistemas/pull/218#discussion_r500024780
- https://github.com/AnhellO/DAS_Sistemas/pull/218#discussion_r500025107
  - https://github.com/AnhellO/DAS_Sistemas/pull/218#discussion_r500025107
- https://github.com/AnhellO/DAS_Sistemas/pull/218#discussion_r500024580

2020-10-12 04:25 UTC, AnhellO requested changes
Siguen estos comentarios pendientes:
- https://github.com/AnhellO/DAS_Sistemas/pull/218#discussion_r500024580
- https://github.com/AnhellO/DAS_Sistemas/pull/218#discussion_r493191567

2020-10-26 05:13 UTC, merged