DAS_Sistemas Develop Push: Practica-4
AnhellO/DAS_Sistemas pull request #225
Opened 2020-09-24 21:50 UTC by Rephyroth

2020-10-07 03:54 UTC, AnhellO requested changes
No veo algún cambio relevante de refactorización contra el código original, tratemos de analizar más a fondo como es que podemos mejorar el código y evitar duplicidad. Te dejo un PDF útil de referencia: https://www.thekua.com/publications/RefactoringCheatSheet.pdf

2020-10-07 03:54 UTC, AnhellO commented on Ago-Dic-2020/flores-fernandez-fernando/Practicas/Practica-4/Practica4.py
> +    def __str__(self):
La función se sigue duplicando a comparación de la función heredada

2020-10-07 03:54 UTC, AnhellO commented on Ago-Dic-2020/flores-fernandez-fernando/Practicas/Practica-4/Practica4.py
> +    def Saludar(self):
Tenemos que cumplir con el pep-8: `snake_case`

2020-10-07 03:54 UTC, AnhellO commented on Ago-Dic-2020/flores-fernandez-fernando/Practicas/Practica-4/Practica4.py
> +class SchoolMemberFactory:
Hace falta un espacio en blanco por aquí, entre ambas clases

2020-10-12 00:59 UTC, Rephyroth commented on Ago-Dic-2020/flores-fernandez-fernando/Practicas/Practica-4/Practica4.py
> +    def __str__(self):
modifique la funcion para que ya no se duplique

2020-10-12 01:00 UTC, Rephyroth commented on Ago-Dic-2020/flores-fernandez-fernando/Practicas/Practica-4/Practica4.py
> +    def Saludar(self):
esta practica creo que la hice antes de leer el pep-8, pero ya está todo

2020-10-12 01:02 UTC, Rephyroth commented on Ago-Dic-2020/flores-fernandez-fernando/Practicas/Practica-4/Practica4.py
> +    def __str__(self):
y alteré el método para la verificación de los kinds, es lo que pude encontrar para simplificar el código, mas aparte otras dos validaciones

2020-10-12 04:30 UTC, AnhellO approved these changes

2020-10-12 04:33 UTC, merged