DAS_Sistemas Develop Push: Practica-3
AnhellO/DAS_Sistemas pull request #229
Opened 2020-10-03 19:10 UTC by Arbupa

2020-10-06 06:20 UTC, AnhellO requested changes
Dejé algunos de comentarios

2020-10-06 06:20 UTC, AnhellO commented on Ago-Dic-2020/chavez-muñoz-juan-arnoldo/Practica-1/Practica-1.py
> +class Matrix:
Hay que remover los archivos que no pertenezcan a la práctica correspondiente

2020-10-06 06:20 UTC, AnhellO commented on Ago-Dic-2020/chavez-muñoz-juan-arnoldo/Practica-2/Practica-2.py
> +class Carro(object):
Este también tiene que removerse (ya está siendo revisado en otra branch)

2020-10-06 06:20 UTC, AnhellO commented on Ago-Dic-2020/chavez-muñoz-juan-arnoldo/Practica-3/Prototype_test.py
> +        sde = SDE()
Acá tenemos indentación de más, hay que ajustarla a que sea toda consistente en el mismo archivo (o grupo de archivos)

2020-10-07 01:47 UTC, AnhellO requested changes
Cambio menor

2020-10-07 01:47 UTC, AnhellO commented on Ago-Dic-2020/chavez-muñoz-juan-arnoldo/Practica-3/.cache/v/cache/lastfailed
> +{
Este archivo no es necesario

2020-10-07 01:48 UTC, AnhellO commented
Están pendientes estos comentarios:
- https://github.com/AnhellO/DAS_Sistemas/pull/229#discussion_r500029401
- https://github.com/AnhellO/DAS_Sistemas/pull/229#discussion_r500029521

2020-10-07 02:07 UTC, Arbupa commented
Acabo de hacer el push ahora sí asegurándome que borré esos archivos extra, pero creo que cerró la pull request y dice "branch has unmerged commits", ¿ahí necesito abrirla de nuevo para que se haga el merge o qué rock?

2020-10-07 02:28 UTC, AnhellO commented
> Acabo de hacer el push ahora sí asegurándome que borré esos archivos extra, pero creo que cerró la pull request y dice "branch has unmerged commits", ¿ahí necesito abrirla de nuevo para que se haga el merge o qué rock?

Ya lo re-abrí @Arbupa 👍

2020-10-12 04:44 UTC, AnhellO requested changes
Sigo viendo archivos que no corresponden a la práctica 3:
- https://github.com/AnhellO/DAS_Sistemas/pull/229#discussion_r500029521
- https://github.com/AnhellO/DAS_Sistemas/pull/229/files

2020-10-26 05:16 UTC, merged