DAS_Sistemas development push: Práctica 1
AnhellO/DAS_Sistemas pull request #6
Opened 2017-09-07 21:07 UTC by jvillarreal7

Dejo mi pull request de la práctica 1 para code review o lo que se necesite.
Saludos.

2017-09-11 04:25 UTC, AnhellO requested changes
Un par de comentarios @jvillarreal7, pero en general, buen trabajo, me fue relativamente rápido testear tus clases individualmente, y la práctica en conjunto gracias a que creaste instancias y las dejaste comentadas para rápido testeo 👍

2017-09-11 04:25 UTC, AnhellO commented on Ago-Dic-2017/Jaime Villarreal/Práctica 1/.gitignore
> +__pycache__
Movamos el archivo `.gitignore` a la carpeta principal del repositorio, por favor

2017-09-11 04:25 UTC, AnhellO commented on Ago-Dic-2017/Jaime Villarreal/Práctica 1/main.py
> +            elif action == '5':
Una validación por acá vendría bien

<img width="799" alt="screenshot 2017-09-10 23 06 23" src="https://user-images.githubusercontent.com/7515146/30258433-006ad55c-967f-11e7-9438-5696b05df881.png">

2017-09-12 01:55 UTC, jvillarreal7 commented
Hice los cambios solicitados.

2017-09-12 03:50 UTC, AnhellO approved these changes

2017-09-12 03:52 UTC, AnhellO commented
Bien Jimmy! 👍 , no hagamos merge aún, por favor

2017-09-14 04:42 UTC, merged