DAS_Sistemas development push: Clases y diagrama
AnhellO/DAS_Sistemas pull request #7
Opened 2017-09-08 18:22 UTC by CMAREQ

Mi proyecto algo largo, pero funcional :D.

2017-09-11 05:02 UTC, AnhellO requested changes
Buen trabajo Cuau, parece ser que la agencia de vehículos chidos Pokimon tiene futuro 👍 

Aparte de eso, dejé un par de comentarios después de revisarlo. Algo que nos falto por acá fue el diagrama de actividades de UML 😞

2017-09-11 05:02 UTC, AnhellO commented on Ago-Dic_2017/Martinez Requenes Cuauhtemoc/Practica1/main.py
> +            input("Pulse 5 para continuar: ")
Parece ser que con un enter salimos

<img width="599" alt="screenshot 2017-09-10 23 57 16" src="https://user-images.githubusercontent.com/7515146/30259048-1635d1a2-9684-11e7-96a5-df559217f63c.png">

2017-09-11 05:02 UTC, AnhellO commented on Ago-Dic_2017/Martinez Requenes Cuauhtemoc/Practica1/vehiculo.py
> +    def decrementaExist(self, menos):
Una validación no vendría mal por acá

<img width="445" alt="screenshot 2017-09-10 23 56 01" src="https://user-images.githubusercontent.com/7515146/30259035-f6800508-9683-11e7-8ff0-c6f80871ae8a.png">

2017-09-11 05:06 UTC, AnhellO commented
Otro punto que se me pasó comentarte. Creo que tu fork no está actualizado con los cambios más recientes en el repo de la materia Cuau:

<img width="607" alt="screenshot 2017-09-11 00 03 56" src="https://user-images.githubusercontent.com/7515146/30259137-cb8241d0-9684-11e7-98f9-cf8445aba885.png">

Tendrás que actualizarlo antes de mergear tus cambios. De igual manera, para la carpeta de alumno solamente basta con que coloques tu primer nombre y primer apellido ej. `Cuauhtemoc Martínez/Práctica 1`. Déjame saber si tienes alguna duda 👍

2017-09-11 20:57 UTC, CMAREQ commented
Cambios realizados, también actualicé el fork con lo agregado recientemente 😄

2017-09-13 04:33 UTC, AnhellO approved these changes

2017-09-13 04:35 UTC, AnhellO commented
Listo Cuau! 👍 

Una vez que Jaime haga merge de su práctica, puedes hacer merge de la tuya también. Ojo, solamente hasta el branch de `development` por favor.

2017-09-14 04:42 UTC, merged