Agencia.
AnhellO/DAS_Sistemas pull request #8
Opened 2017-09-10 02:40 UTC by fanborges

2017-09-11 06:18 UTC, AnhellO requested changes
Buen trabajo Clemente, una full cli app de la práctica de la Agencia, utilizando otras librerías nativas del lenguaje y experimentando con cosas diferentes. También vi buen manejo de excepciones 👍 . Hay algunas cosas que podrían mejorarse, sobre todo en el lado de la ayuda y la descripción (visto desde el lado del usuario, es tedioso tener que utilizar `help` en múltiples ocasiones para saber que hacer). También podrías haber creado una instancia de ejemplo para cada entidad, directo en el código, ya que eso facilitaría un testeo más rápido.

Algo que falto, fue el diagrama de actividades. Ese ayudaría un poco más a saber como funciona tu cli app sin tener que utilizar tanto `help`.

En general, comentarios relacionados a la usabilidad nada más. Ah, y a la validación de existencias.

2017-09-11 06:18 UTC, AnhellO commented on Ago-Dic-2017/Luis_Clemente_Zúñiga_Flores/Práctica_1/.gitignore
> +Prueba.py
Una vez que Jaime agregue el `.gitignore` a la carpeta principal del repo, movamos estas declaraciones de archivos a ese mismo file, por favor

2017-09-11 06:18 UTC, AnhellO commented on Ago-Dic-2017/Luis_Clemente_Zúñiga_Flores/Práctica_1/Persona.py
> +    """Abstract class Persona
Esta no sería un clase abstracta, solamente sería una clase base, pero funcional por sí sola

2017-09-11 06:18 UTC, AnhellO commented on Ago-Dic-2017/Luis_Clemente_Zúñiga_Flores/Práctica_1/Vehiculo.py
> +    """Abstract class Vehiculo
Lo mismo que en la clase `Persona`

2017-09-11 06:18 UTC, AnhellO commented on Ago-Dic-2017/Luis_Clemente_Zúñiga_Flores/Práctica_1/Vehiculo.py
> +        self.__existencia-=1
Una validación vendría bien aquí:

<img width="721" alt="screenshot 2017-09-11 01 10 00" src="https://user-images.githubusercontent.com/7515146/30260645-41971c0c-968e-11e7-8aec-40c3ec2dfe60.png">

2017-09-11 06:18 UTC, AnhellO commented on Ago-Dic-2017/Luis_Clemente_Zúñiga_Flores/Práctica_1/Ayuda.py
> +        print('\n\t<<clientes>> arroja una lista de los clientes con su respectiva información.')
Hizo falta consulta empleados en la descripción de la ayuda :(

2017-09-11 06:18 UTC, AnhellO commented on Ago-Dic-2017/Luis_Clemente_Zúñiga_Flores/Práctica_1/Ayuda.py
> +        print('<<cliente>> [\'nombre\' \'ap. paterno\' \'ap. materno\' \'edad\' \'dirección\' \n\t\t\'teléfono\']')
Falto el género en los parámetros.

2017-09-11 06:21 UTC, AnhellO commented
Un punto que se me pasó comentarte Clemente, no olvides apegarte a la [forma de contribuir en el repo](https://github.com/AnhellO/DAS_Sistemas#contributing), por favor

<img width="785" alt="screenshot 2017-09-11 01 20 01" src="https://user-images.githubusercontent.com/7515146/30260870-761100a0-968f-11e7-8214-d9e60f2e328e.png">

2017-09-11 06:41 UTC, fanborges commented
Perdón, de plano se me barrió la especificación al momento de hacer el pull request :(

2017-09-13 04:59 UTC, AnhellO commented
Bien Clemente! 👍 , ya solamente faltaría actualizar el nombre de tu carpeta de alumno para que se apega al [estándar de contribución](https://github.com/AnhellO/DAS_Sistemas#contributing). Debería de quedar como `Ago-Dic-2017/Luis Zúñiga/...`

2017-09-13 15:35 UTC, AnhellO commented
Bien, Clemente! 👍 

Espera a que Jaime haga merge de su práctica, por favor, para que puedas agregar los archivos que tenías en el `.gitignore`, y después hacer merge. Ojo, solamente hasta el branch de `development` por favor.

2017-09-13 15:35 UTC, AnhellO approved these changes

2017-09-14 04:43 UTC, merged