Practica 1- Cynthia García
AnhellO/DAS_Sistemas pull request #99
Opened 2018-08-30 02:26 UTC by 270991

Tarea Número 1

2018-10-03 06:28 UTC, AnhellO requested changes
Qué tal @Cynthia,

Deje algunos comentarios. Hay muchas variables que no es necesario crear, y pueden limpiarse/optimizarse, pero solamente deje algunos rastros de ellas en algunos de los comentarios que te deje 👍

2018-10-03 06:28 UTC, AnhellO commented on Ago-Dic-2018/CynthiaGarcía/ComandosGit.md
> +Comandos Basicos de Git:
Este es un archivo markdown. Posiblemente deberías de utilizar algo de la sintaxis de markdown para darle formato a tu archivo https://www.markdowntutorial.com/

2018-10-03 06:28 UTC, AnhellO commented on Ago-Dic-2018/CynthiaGarcía/ComandosGit.md
> +se usa para agregar una descripci�n o comentario de los archivos que deseaas agregar al repositorio.
Para referencia, `git commit` hace más que eso https://git-scm.com/docs/git-commit

2018-10-03 06:28 UTC, AnhellO commented on Ago-Dic-2018/CynthiaGarcía/MagiciansDA.py
> +		mago+='The great'
Un espacio antes de `The great` vendría bien, de lo contrario la lista resultante será `['MerlinThe great', 'HoudiniThe great', 'PotterThe great']`

2018-10-03 06:28 UTC, AnhellO commented on Ago-Dic-2018/CynthiaGarcía/MagiciansDA.py
> +#Esta funcion es opcional para mostrar el 8-11,
En teoría, deberías de haber utilizado la misma función `make_great` en el ejercicio `8-11`

<img width="490" alt="screenshot 2018-10-03 00 59 17" src="https://user-images.githubusercontent.com/7515146/46392624-936c8180-c6a7-11e8-97fe-19165f19053e.png">

2018-10-03 06:28 UTC, AnhellO commented on Ago-Dic-2018/CynthiaGarcía/Restaurant.py
> +		aux="El" + self.nombre + "esta Abierto"
Un espacio en blanco antes de `esta Abierto` vendría bien 👍

2018-10-03 06:28 UTC, AnhellO commented on Ago-Dic-2018/CynthiaGarcía/Restaurant.py
> +		aux="Nombre:"+ self.nombre + "\n"+"Tipo:"+ self.cuisine_type
Esto está bien, pero aquí podías haber utilizado la función `format`, sin necesidad de crear una nueva variable (`aux`)

2018-10-03 06:28 UTC, AnhellO commented on Ago-Dic-2018/CynthiaGarcía/User.py
> +	def increment_login(self):
¿Qué sucede acá si yo llamó `increment_login` 2 o más veces seguidas para un mismo objeto? 🤔

2018-10-03 06:28 UTC, AnhellO commented on Ago-Dic-2018/CynthiaGarcía/User.py
> +prit("\n")
Esto va a fallar 😞

2018-10-03 06:28 UTC, AnhellO commented on Ago-Dic-2018/CynthiaGarcía/User.py
> +	def increment_login(self):
Otro punto: ¿Porque estamos imprimiendo los datos del usuario aquí, cuando no es requerido?

2018-10-03 06:28 UTC, AnhellO commented on Ago-Dic-2018/CynthiaGarcía/User.py
> +	def reset_login(self):
No creo que esto vaya a funcionar como se espera, estás declarando una nueva variable `ix`, pero no haces nada con el atributo de clase `self.login_attempts`

2018-10-03 06:28 UTC, AnhellO commented on Ago-Dic-2018/CynthiaGarcía/NumServ.py
> +		return('Name:{}, \nType:{}, \nServicio:{}'.format(self.nombre, self.cuisine_type, self.number_server))
No hay necesidad de colocar paréntesis alrededor del string que se está regresando, es decir, `return 'Name:{}, \nType:{}, \nServicio:{}'.format(self.nombre, self.cuisine_type, self.number_server)` se suficiente

2018-10-30 05:52 UTC, AnhellO approved these changes

2018-10-30 06:04 UTC, AnhellO requested changes
Un último cambio Cynthia. ¿Podrías organizar todos tus archivos por carpetas, por favor?, es decir:
* `/practica-1/{todos los archivos de la práctica 1}`
* `/practica-2/{todos los archivos de la práctica 2}`
* `/examen-1er-parcial/{todos los archivos del primer examen parcial}`

Y así sucesivamente 😄

2018-10-30 06:19 UTC, AnhellO approved these changes

2018-10-30 06:19 UTC, merged

2018-10-30 13:28 UTC, 270991 commented
Si, estaba bien, ya lo organizo. :)

On Tue, Oct 30, 2018, 12:04 AM Angel Santiago Jaime Zavala <
notifications@github.com> wrote:

> *@AnhellO* requested changes on this pull request.
>
> Un último cambio Cynthia. ¿Podrías organizar todos tus archivos por
> carpetas, por favor?, es decir:
>
>    - /practica-1/{todos los archivos de la práctica 1}
>    - /practica-2/{todos los archivos de la práctica 2}
>    - /examen-1er-parcial/{todos los archivos del primer examen parcial}
>
> Y así sucesivamente 😄
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/AnhellO/DAS_Sistemas/pull/99#pullrequestreview-169622304>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AiH29d1TsZG29syZsnuTXWFaaNPmx_LUks5up-vsgaJpZM4WSqno>
> .
>